/**
  * \file VecMsdcVDpch.h
  * vector VecMsdcVDpch (declarations)
  * \author Alexander Wirthmueller
  * \date created: 18 Dec 2018
  * \date modified: 18 Dec 2018
  */

#ifndef VECMSDCVDPCH_H
#define VECMSDCVDPCH_H

#include <sbecore/Xmlio.h>

using namespace Xmlio;

/**
	* VecMsdcVDpch
	*/
namespace VecMsdcVDpch {
	const uint DPCHAPPDLGMSDCFILDOWNLOADDO = 1;
	const uint DPCHAPPDLGMSDCNAVLOAINIDATA = 2;
	const uint DPCHAPPDLGMSDCNAVLOAINIDO = 3;
	const uint DPCHAPPMSDCALERT = 4;
	const uint DPCHAPPMSDCDATAPARDATA = 5;
	const uint DPCHAPPMSDCDATAPARDO = 6;
	const uint DPCHAPPMSDCDATDETAILDATA = 7;
	const uint DPCHAPPMSDCDATDETAILDO = 8;
	const uint DPCHAPPMSDCDATDO = 9;
	const uint DPCHAPPMSDCDATLISTDATA = 10;
	const uint DPCHAPPMSDCDATLISTDO = 11;
	const uint DPCHAPPMSDCDATRECDO = 12;
	const uint DPCHAPPMSDCDATREF1NFILEDATA = 13;
	const uint DPCHAPPMSDCDATREF1NFILEDO = 14;
	const uint DPCHAPPMSDCFILDETAILDATA = 15;
	const uint DPCHAPPMSDCFILDETAILDO = 16;
	const uint DPCHAPPMSDCFILDO = 17;
	const uint DPCHAPPMSDCFILLISTDATA = 18;
	const uint DPCHAPPMSDCFILLISTDO = 19;
	const uint DPCHAPPMSDCFILRECDO = 20;
	const uint DPCHAPPMSDCINIT = 21;
	const uint DPCHAPPMSDCLIVALIGNDATA = 22;
	const uint DPCHAPPMSDCLIVALIGNDO = 23;
	const uint DPCHAPPMSDCLIVDO = 24;
	const uint DPCHAPPMSDCLIVSCILLDATA = 25;
	const uint DPCHAPPMSDCLIVSCILLDO = 26;
	const uint DPCHAPPMSDCLIVTRACKDATA = 27;
	const uint DPCHAPPMSDCLIVTRACKDO = 28;
	const uint DPCHAPPMSDCLIVVIDEODATA = 29;
	const uint DPCHAPPMSDCLIVVIDEODO = 30;
	const uint DPCHAPPMSDCNAVADMINDATA = 31;
	const uint DPCHAPPMSDCNAVADMINDO = 32;
	const uint DPCHAPPMSDCNAVDO = 33;
	const uint DPCHAPPMSDCNAVOPRDATA = 34;
	const uint DPCHAPPMSDCNAVOPRDO = 35;
	const uint DPCHAPPMSDCNAVPREDO = 36;
	const uint DPCHAPPMSDCPRD1NDATADATA = 37;
	const uint DPCHAPPMSDCPRD1NDATADO = 38;
	const uint DPCHAPPMSDCPRDDETAILDATA = 39;
	const uint DPCHAPPMSDCPRDDETAILDO = 40;
	const uint DPCHAPPMSDCPRDDO = 41;
	const uint DPCHAPPMSDCPRDLISTDATA = 42;
	const uint DPCHAPPMSDCPRDLISTDO = 43;
	const uint DPCHAPPMSDCPRDRECDO = 44;
	const uint DPCHAPPMSDCPRSDETAILDATA = 45;
	const uint DPCHAPPMSDCPRSDETAILDO = 46;
	const uint DPCHAPPMSDCPRSDO = 47;
	const uint DPCHAPPMSDCPRSLISTDATA = 48;
	const uint DPCHAPPMSDCPRSLISTDO = 49;
	const uint DPCHAPPMSDCPRSRECDO = 50;
	const uint DPCHAPPMSDCRESUME = 51;
	const uint DPCHAPPMSDCSCFACQUISDATA = 52;
	const uint DPCHAPPMSDCSCFACQUISDO = 53;
	const uint DPCHAPPMSDCSCFACTUDATA = 54;
	const uint DPCHAPPMSDCSCFACTUDO = 55;
	const uint DPCHAPPMSDCSCFDO = 56;
	const uint DPCHAPPMSDCSCFPRCCTLDO = 57;
	const uint DPCHAPPMSDCSCFSOURCEDATA = 58;
	const uint DPCHAPPMSDCSCFSOURCEDO = 59;
	const uint DPCHAPPMSDCUSGAACCESSDATA = 60;
	const uint DPCHAPPMSDCUSGAACCESSDO = 61;
	const uint DPCHAPPMSDCUSGDETAILDATA = 62;
	const uint DPCHAPPMSDCUSGDETAILDO = 63;
	const uint DPCHAPPMSDCUSGDO = 64;
	const uint DPCHAPPMSDCUSGLISTDATA = 65;
	const uint DPCHAPPMSDCUSGLISTDO = 66;
	const uint DPCHAPPMSDCUSGMNUSERDATA = 67;
	const uint DPCHAPPMSDCUSGMNUSERDO = 68;
	const uint DPCHAPPMSDCUSGRECDO = 69;
	const uint DPCHAPPMSDCUSR1NSESSIONDATA = 70;
	const uint DPCHAPPMSDCUSR1NSESSIONDO = 71;
	const uint DPCHAPPMSDCUSRAACCESSDATA = 72;
	const uint DPCHAPPMSDCUSRAACCESSDO = 73;
	const uint DPCHAPPMSDCUSRDETAILDATA = 74;
	const uint DPCHAPPMSDCUSRDETAILDO = 75;
	const uint DPCHAPPMSDCUSRDO = 76;
	const uint DPCHAPPMSDCUSRLISTDATA = 77;
	const uint DPCHAPPMSDCUSRLISTDO = 78;
	const uint DPCHAPPMSDCUSRMNUSERGROUPDATA = 79;
	const uint DPCHAPPMSDCUSRMNUSERGROUPDO = 80;
	const uint DPCHAPPMSDCUSRRECDO = 81;
	const uint DPCHAPPROOTMSDCLOGIN = 82;
	const uint DPCHENGDLGMSDCFILDOWNLOADDATA = 83;
	const uint DPCHENGDLGMSDCNAVLOAINIDATA = 84;
	const uint DPCHENGM2MSESSMSDCDATA = 85;
	const uint DPCHENGMSDCACK = 86;
	const uint DPCHENGMSDCALERT = 87;
	const uint DPCHENGMSDCCONFIRM = 88;
	const uint DPCHENGMSDCDATAPARDATA = 89;
	const uint DPCHENGMSDCDATDATA = 90;
	const uint DPCHENGMSDCDATDETAILDATA = 91;
	const uint DPCHENGMSDCDATHEADBARDATA = 92;
	const uint DPCHENGMSDCDATLISTDATA = 93;
	const uint DPCHENGMSDCDATRECDATA = 94;
	const uint DPCHENGMSDCDATREF1NFILEDATA = 95;
	const uint DPCHENGMSDCFILDATA = 96;
	const uint DPCHENGMSDCFILDETAILDATA = 97;
	const uint DPCHENGMSDCFILHEADBARDATA = 98;
	const uint DPCHENGMSDCFILLISTDATA = 99;
	const uint DPCHENGMSDCFILRECDATA = 100;
	const uint DPCHENGMSDCLIVALIGNDATA = 101;
	const uint DPCHENGMSDCLIVDATA = 102;
	const uint DPCHENGMSDCLIVHEADBARDATA = 103;
	const uint DPCHENGMSDCLIVSCILLDATA = 104;
	const uint DPCHENGMSDCLIVTRACKDATA = 105;
	const uint DPCHENGMSDCLIVVIDEODATA = 106;
	const uint DPCHENGMSDCLIVVIDEOLIVE = 107;
	const uint DPCHENGMSDCNAVADMINDATA = 108;
	const uint DPCHENGMSDCNAVDATA = 109;
	const uint DPCHENGMSDCNAVHEADBARDATA = 110;
	const uint DPCHENGMSDCNAVOPRDATA = 111;
	const uint DPCHENGMSDCNAVPREDATA = 112;
	const uint DPCHENGMSDCPRD1NDATADATA = 113;
	const uint DPCHENGMSDCPRDDATA = 114;
	const uint DPCHENGMSDCPRDDETAILDATA = 115;
	const uint DPCHENGMSDCPRDHEADBARDATA = 116;
	const uint DPCHENGMSDCPRDLISTDATA = 117;
	const uint DPCHENGMSDCPRDRECDATA = 118;
	const uint DPCHENGMSDCPRSDATA = 119;
	const uint DPCHENGMSDCPRSDETAILDATA = 120;
	const uint DPCHENGMSDCPRSHEADBARDATA = 121;
	const uint DPCHENGMSDCPRSLISTDATA = 122;
	const uint DPCHENGMSDCPRSRECDATA = 123;
	const uint DPCHENGMSDCSCFACQUISDATA = 124;
	const uint DPCHENGMSDCSCFACTUDATA = 125;
	const uint DPCHENGMSDCSCFDATA = 126;
	const uint DPCHENGMSDCSCFHEADBARDATA = 127;
	const uint DPCHENGMSDCSCFPRCCTLDATA = 128;
	const uint DPCHENGMSDCSCFSOURCEDATA = 129;
	const uint DPCHENGMSDCSUSPEND = 130;
	const uint DPCHENGMSDCUSGAACCESSDATA = 131;
	const uint DPCHENGMSDCUSGDATA = 132;
	const uint DPCHENGMSDCUSGDETAILDATA = 133;
	const uint DPCHENGMSDCUSGHEADBARDATA = 134;
	const uint DPCHENGMSDCUSGLISTDATA = 135;
	const uint DPCHENGMSDCUSGMNUSERDATA = 136;
	const uint DPCHENGMSDCUSGRECDATA = 137;
	const uint DPCHENGMSDCUSR1NSESSIONDATA = 138;
	const uint DPCHENGMSDCUSRAACCESSDATA = 139;
	const uint DPCHENGMSDCUSRDATA = 140;
	const uint DPCHENGMSDCUSRDETAILDATA = 141;
	const uint DPCHENGMSDCUSRHEADBARDATA = 142;
	const uint DPCHENGMSDCUSRLISTDATA = 143;
	const uint DPCHENGMSDCUSRMNUSERGROUPDATA = 144;
	const uint DPCHENGMSDCUSRRECDATA = 145;
	const uint DPCHENGROOTMSDCDATA = 146;
	const uint DPCHENGSESSMSDCDATA = 147;
	const uint DPCHINVMSDC = 148;
	const uint DPCHMSDCDACK = 149;
	const uint DPCHMSDCDQUIT = 150;
	const uint DPCHMSDCDREG = 151;
	const uint DPCHMSDCOPDREG = 152;
	const uint DPCHMSDCOPDUNREG = 153;
	const uint DPCHRETMSDC = 154;

	uint getIx(const string& sref);
	string getSref(const uint ix);
};

#endif

