/**
  * \file VecMsdcVDpch.h
  * vector VecMsdcVDpch (declarations)
  * \author Alexander Wirthmueller
  * \date created: 12 Sep 2018
  * \date modified: 12 Sep 2018
  */

#ifndef VECMSDCVDPCH_H
#define VECMSDCVDPCH_H

#include <sbecore/Xmlio.h>

using namespace Xmlio;

/**
	* VecMsdcVDpch
	*/
namespace VecMsdcVDpch {
	const uint DPCHAPPDLGMSDCFILDOWNLOADDO = 1;
	const uint DPCHAPPDLGMSDCNAVLOAINIDATA = 2;
	const uint DPCHAPPDLGMSDCNAVLOAINIDO = 3;
	const uint DPCHAPPMSDCALERT = 4;
	const uint DPCHAPPMSDCDATAPARDATA = 5;
	const uint DPCHAPPMSDCDATAPARDO = 6;
	const uint DPCHAPPMSDCDATDETAILDATA = 7;
	const uint DPCHAPPMSDCDATDETAILDO = 8;
	const uint DPCHAPPMSDCDATDO = 9;
	const uint DPCHAPPMSDCDATLISTDATA = 10;
	const uint DPCHAPPMSDCDATLISTDO = 11;
	const uint DPCHAPPMSDCDATRECDO = 12;
	const uint DPCHAPPMSDCDATREF1NFILEDATA = 13;
	const uint DPCHAPPMSDCDATREF1NFILEDO = 14;
	const uint DPCHAPPMSDCFILDETAILDATA = 15;
	const uint DPCHAPPMSDCFILDETAILDO = 16;
	const uint DPCHAPPMSDCFILDO = 17;
	const uint DPCHAPPMSDCFILLISTDATA = 18;
	const uint DPCHAPPMSDCFILLISTDO = 19;
	const uint DPCHAPPMSDCFILRECDO = 20;
	const uint DPCHAPPMSDCINIT = 21;
	const uint DPCHAPPMSDCLIVALIGNDATA = 22;
	const uint DPCHAPPMSDCLIVALIGNDO = 23;
	const uint DPCHAPPMSDCLIVDO = 24;
	const uint DPCHAPPMSDCLIVSCILLDATA = 25;
	const uint DPCHAPPMSDCLIVSCILLDO = 26;
	const uint DPCHAPPMSDCLIVTRACKDO = 27;
	const uint DPCHAPPMSDCLIVVIDEODATA = 28;
	const uint DPCHAPPMSDCLIVVIDEODO = 29;
	const uint DPCHAPPMSDCNAVADMINDATA = 30;
	const uint DPCHAPPMSDCNAVADMINDO = 31;
	const uint DPCHAPPMSDCNAVDO = 32;
	const uint DPCHAPPMSDCNAVOPRDATA = 33;
	const uint DPCHAPPMSDCNAVOPRDO = 34;
	const uint DPCHAPPMSDCNAVPREDO = 35;
	const uint DPCHAPPMSDCPRD1NDATADATA = 36;
	const uint DPCHAPPMSDCPRD1NDATADO = 37;
	const uint DPCHAPPMSDCPRDDETAILDATA = 38;
	const uint DPCHAPPMSDCPRDDETAILDO = 39;
	const uint DPCHAPPMSDCPRDDO = 40;
	const uint DPCHAPPMSDCPRDLISTDATA = 41;
	const uint DPCHAPPMSDCPRDLISTDO = 42;
	const uint DPCHAPPMSDCPRDRECDO = 43;
	const uint DPCHAPPMSDCPRSDETAILDATA = 44;
	const uint DPCHAPPMSDCPRSDETAILDO = 45;
	const uint DPCHAPPMSDCPRSDO = 46;
	const uint DPCHAPPMSDCPRSLISTDATA = 47;
	const uint DPCHAPPMSDCPRSLISTDO = 48;
	const uint DPCHAPPMSDCPRSRECDO = 49;
	const uint DPCHAPPMSDCRESUME = 50;
	const uint DPCHAPPMSDCSCFACQUISDATA = 51;
	const uint DPCHAPPMSDCSCFACQUISDO = 52;
	const uint DPCHAPPMSDCSCFACTUDATA = 53;
	const uint DPCHAPPMSDCSCFACTUDO = 54;
	const uint DPCHAPPMSDCSCFDO = 55;
	const uint DPCHAPPMSDCSCFPRCCTLDO = 56;
	const uint DPCHAPPMSDCSCFSOURCEDATA = 57;
	const uint DPCHAPPMSDCSCFSOURCEDO = 58;
	const uint DPCHAPPMSDCUSGAACCESSDATA = 59;
	const uint DPCHAPPMSDCUSGAACCESSDO = 60;
	const uint DPCHAPPMSDCUSGDETAILDATA = 61;
	const uint DPCHAPPMSDCUSGDETAILDO = 62;
	const uint DPCHAPPMSDCUSGDO = 63;
	const uint DPCHAPPMSDCUSGLISTDATA = 64;
	const uint DPCHAPPMSDCUSGLISTDO = 65;
	const uint DPCHAPPMSDCUSGMNUSERDATA = 66;
	const uint DPCHAPPMSDCUSGMNUSERDO = 67;
	const uint DPCHAPPMSDCUSGRECDO = 68;
	const uint DPCHAPPMSDCUSR1NSESSIONDATA = 69;
	const uint DPCHAPPMSDCUSR1NSESSIONDO = 70;
	const uint DPCHAPPMSDCUSRAACCESSDATA = 71;
	const uint DPCHAPPMSDCUSRAACCESSDO = 72;
	const uint DPCHAPPMSDCUSRDETAILDATA = 73;
	const uint DPCHAPPMSDCUSRDETAILDO = 74;
	const uint DPCHAPPMSDCUSRDO = 75;
	const uint DPCHAPPMSDCUSRLISTDATA = 76;
	const uint DPCHAPPMSDCUSRLISTDO = 77;
	const uint DPCHAPPMSDCUSRMNUSERGROUPDATA = 78;
	const uint DPCHAPPMSDCUSRMNUSERGROUPDO = 79;
	const uint DPCHAPPMSDCUSRRECDO = 80;
	const uint DPCHAPPROOTMSDCLOGIN = 81;
	const uint DPCHENGDLGMSDCFILDOWNLOADDATA = 82;
	const uint DPCHENGDLGMSDCNAVLOAINIDATA = 83;
	const uint DPCHENGM2MSESSMSDCDATA = 84;
	const uint DPCHENGMSDCACK = 85;
	const uint DPCHENGMSDCALERT = 86;
	const uint DPCHENGMSDCCONFIRM = 87;
	const uint DPCHENGMSDCDATAPARDATA = 88;
	const uint DPCHENGMSDCDATDATA = 89;
	const uint DPCHENGMSDCDATDETAILDATA = 90;
	const uint DPCHENGMSDCDATHEADBARDATA = 91;
	const uint DPCHENGMSDCDATLISTDATA = 92;
	const uint DPCHENGMSDCDATRECDATA = 93;
	const uint DPCHENGMSDCDATREF1NFILEDATA = 94;
	const uint DPCHENGMSDCFILDATA = 95;
	const uint DPCHENGMSDCFILDETAILDATA = 96;
	const uint DPCHENGMSDCFILHEADBARDATA = 97;
	const uint DPCHENGMSDCFILLISTDATA = 98;
	const uint DPCHENGMSDCFILRECDATA = 99;
	const uint DPCHENGMSDCLIVALIGNDATA = 100;
	const uint DPCHENGMSDCLIVDATA = 101;
	const uint DPCHENGMSDCLIVHEADBARDATA = 102;
	const uint DPCHENGMSDCLIVSCILLDATA = 103;
	const uint DPCHENGMSDCLIVTRACKDATA = 104;
	const uint DPCHENGMSDCLIVVIDEODATA = 105;
	const uint DPCHENGMSDCLIVVIDEOLIVE = 106;
	const uint DPCHENGMSDCNAVADMINDATA = 107;
	const uint DPCHENGMSDCNAVDATA = 108;
	const uint DPCHENGMSDCNAVHEADBARDATA = 109;
	const uint DPCHENGMSDCNAVOPRDATA = 110;
	const uint DPCHENGMSDCNAVPREDATA = 111;
	const uint DPCHENGMSDCPRD1NDATADATA = 112;
	const uint DPCHENGMSDCPRDDATA = 113;
	const uint DPCHENGMSDCPRDDETAILDATA = 114;
	const uint DPCHENGMSDCPRDHEADBARDATA = 115;
	const uint DPCHENGMSDCPRDLISTDATA = 116;
	const uint DPCHENGMSDCPRDRECDATA = 117;
	const uint DPCHENGMSDCPRSDATA = 118;
	const uint DPCHENGMSDCPRSDETAILDATA = 119;
	const uint DPCHENGMSDCPRSHEADBARDATA = 120;
	const uint DPCHENGMSDCPRSLISTDATA = 121;
	const uint DPCHENGMSDCPRSRECDATA = 122;
	const uint DPCHENGMSDCSCFACQUISDATA = 123;
	const uint DPCHENGMSDCSCFACTUDATA = 124;
	const uint DPCHENGMSDCSCFDATA = 125;
	const uint DPCHENGMSDCSCFHEADBARDATA = 126;
	const uint DPCHENGMSDCSCFPRCCTLDATA = 127;
	const uint DPCHENGMSDCSCFSOURCEDATA = 128;
	const uint DPCHENGMSDCSUSPEND = 129;
	const uint DPCHENGMSDCUSGAACCESSDATA = 130;
	const uint DPCHENGMSDCUSGDATA = 131;
	const uint DPCHENGMSDCUSGDETAILDATA = 132;
	const uint DPCHENGMSDCUSGHEADBARDATA = 133;
	const uint DPCHENGMSDCUSGLISTDATA = 134;
	const uint DPCHENGMSDCUSGMNUSERDATA = 135;
	const uint DPCHENGMSDCUSGRECDATA = 136;
	const uint DPCHENGMSDCUSR1NSESSIONDATA = 137;
	const uint DPCHENGMSDCUSRAACCESSDATA = 138;
	const uint DPCHENGMSDCUSRDATA = 139;
	const uint DPCHENGMSDCUSRDETAILDATA = 140;
	const uint DPCHENGMSDCUSRHEADBARDATA = 141;
	const uint DPCHENGMSDCUSRLISTDATA = 142;
	const uint DPCHENGMSDCUSRMNUSERGROUPDATA = 143;
	const uint DPCHENGMSDCUSRRECDATA = 144;
	const uint DPCHENGROOTMSDCDATA = 145;
	const uint DPCHENGSESSMSDCDATA = 146;
	const uint DPCHINVMSDC = 147;
	const uint DPCHMSDCDACK = 148;
	const uint DPCHMSDCDQUIT = 149;
	const uint DPCHMSDCDREG = 150;
	const uint DPCHMSDCOPDREG = 151;
	const uint DPCHMSDCOPDUNREG = 152;
	const uint DPCHRETMSDC = 153;

	uint getIx(const string& sref);
	string getSref(const uint ix);
};

#endif

