/**
  * \file VecMsdcVDpch.java
  * vector VecMsdcVDpch
  * \author Alexander Wirthmueller
  * \date created: 12 Sep 2018
  * \date modified: 12 Sep 2018
  */

package apimsdc;

public class VecMsdcVDpch {

	public static final int DPCHENGDLGMSDCFILDOWNLOADDATA = 1;
	public static final int DPCHENGDLGMSDCNAVLOAINIDATA = 2;
	public static final int DPCHENGM2MSESSMSDCDATA = 3;
	public static final int DPCHENGMSDCACK = 4;
	public static final int DPCHENGMSDCALERT = 5;
	public static final int DPCHENGMSDCCONFIRM = 6;
	public static final int DPCHENGMSDCDATAPARDATA = 7;
	public static final int DPCHENGMSDCDATDATA = 8;
	public static final int DPCHENGMSDCDATDETAILDATA = 9;
	public static final int DPCHENGMSDCDATHEADBARDATA = 10;
	public static final int DPCHENGMSDCDATLISTDATA = 11;
	public static final int DPCHENGMSDCDATRECDATA = 12;
	public static final int DPCHENGMSDCDATREF1NFILEDATA = 13;
	public static final int DPCHENGMSDCFILDATA = 14;
	public static final int DPCHENGMSDCFILDETAILDATA = 15;
	public static final int DPCHENGMSDCFILHEADBARDATA = 16;
	public static final int DPCHENGMSDCFILLISTDATA = 17;
	public static final int DPCHENGMSDCFILRECDATA = 18;
	public static final int DPCHENGMSDCLIVALIGNDATA = 19;
	public static final int DPCHENGMSDCLIVDATA = 20;
	public static final int DPCHENGMSDCLIVHEADBARDATA = 21;
	public static final int DPCHENGMSDCLIVSCILLDATA = 22;
	public static final int DPCHENGMSDCLIVTRACKDATA = 23;
	public static final int DPCHENGMSDCLIVVIDEODATA = 24;
	public static final int DPCHENGMSDCLIVVIDEOLIVE = 25;
	public static final int DPCHENGMSDCNAVADMINDATA = 26;
	public static final int DPCHENGMSDCNAVDATA = 27;
	public static final int DPCHENGMSDCNAVHEADBARDATA = 28;
	public static final int DPCHENGMSDCNAVOPRDATA = 29;
	public static final int DPCHENGMSDCNAVPREDATA = 30;
	public static final int DPCHENGMSDCPRD1NDATADATA = 31;
	public static final int DPCHENGMSDCPRDDATA = 32;
	public static final int DPCHENGMSDCPRDDETAILDATA = 33;
	public static final int DPCHENGMSDCPRDHEADBARDATA = 34;
	public static final int DPCHENGMSDCPRDLISTDATA = 35;
	public static final int DPCHENGMSDCPRDRECDATA = 36;
	public static final int DPCHENGMSDCPRSDATA = 37;
	public static final int DPCHENGMSDCPRSDETAILDATA = 38;
	public static final int DPCHENGMSDCPRSHEADBARDATA = 39;
	public static final int DPCHENGMSDCPRSLISTDATA = 40;
	public static final int DPCHENGMSDCPRSRECDATA = 41;
	public static final int DPCHENGMSDCSCFACQUISDATA = 42;
	public static final int DPCHENGMSDCSCFACTUDATA = 43;
	public static final int DPCHENGMSDCSCFDATA = 44;
	public static final int DPCHENGMSDCSCFHEADBARDATA = 45;
	public static final int DPCHENGMSDCSCFPRCCTLDATA = 46;
	public static final int DPCHENGMSDCSCFSOURCEDATA = 47;
	public static final int DPCHENGMSDCSUSPEND = 48;
	public static final int DPCHENGMSDCUSGAACCESSDATA = 49;
	public static final int DPCHENGMSDCUSGDATA = 50;
	public static final int DPCHENGMSDCUSGDETAILDATA = 51;
	public static final int DPCHENGMSDCUSGHEADBARDATA = 52;
	public static final int DPCHENGMSDCUSGLISTDATA = 53;
	public static final int DPCHENGMSDCUSGMNUSERDATA = 54;
	public static final int DPCHENGMSDCUSGRECDATA = 55;
	public static final int DPCHENGMSDCUSR1NSESSIONDATA = 56;
	public static final int DPCHENGMSDCUSRAACCESSDATA = 57;
	public static final int DPCHENGMSDCUSRDATA = 58;
	public static final int DPCHENGMSDCUSRDETAILDATA = 59;
	public static final int DPCHENGMSDCUSRHEADBARDATA = 60;
	public static final int DPCHENGMSDCUSRLISTDATA = 61;
	public static final int DPCHENGMSDCUSRMNUSERGROUPDATA = 62;
	public static final int DPCHENGMSDCUSRRECDATA = 63;
	public static final int DPCHENGROOTMSDCDATA = 64;
	public static final int DPCHENGSESSMSDCDATA = 65;
	public static final int DPCHAPPDLGMSDCFILDOWNLOADDO = 66;
	public static final int DPCHAPPDLGMSDCNAVLOAINIDATA = 67;
	public static final int DPCHAPPDLGMSDCNAVLOAINIDO = 68;
	public static final int DPCHAPPMSDCALERT = 69;
	public static final int DPCHAPPMSDCDATAPARDATA = 70;
	public static final int DPCHAPPMSDCDATAPARDO = 71;
	public static final int DPCHAPPMSDCDATDETAILDATA = 72;
	public static final int DPCHAPPMSDCDATDETAILDO = 73;
	public static final int DPCHAPPMSDCDATDO = 74;
	public static final int DPCHAPPMSDCDATLISTDATA = 75;
	public static final int DPCHAPPMSDCDATLISTDO = 76;
	public static final int DPCHAPPMSDCDATRECDO = 77;
	public static final int DPCHAPPMSDCDATREF1NFILEDATA = 78;
	public static final int DPCHAPPMSDCDATREF1NFILEDO = 79;
	public static final int DPCHAPPMSDCFILDETAILDATA = 80;
	public static final int DPCHAPPMSDCFILDETAILDO = 81;
	public static final int DPCHAPPMSDCFILDO = 82;
	public static final int DPCHAPPMSDCFILLISTDATA = 83;
	public static final int DPCHAPPMSDCFILLISTDO = 84;
	public static final int DPCHAPPMSDCFILRECDO = 85;
	public static final int DPCHAPPMSDCINIT = 86;
	public static final int DPCHAPPMSDCLIVALIGNDATA = 87;
	public static final int DPCHAPPMSDCLIVALIGNDO = 88;
	public static final int DPCHAPPMSDCLIVDO = 89;
	public static final int DPCHAPPMSDCLIVSCILLDATA = 90;
	public static final int DPCHAPPMSDCLIVSCILLDO = 91;
	public static final int DPCHAPPMSDCLIVTRACKDO = 92;
	public static final int DPCHAPPMSDCLIVVIDEODATA = 93;
	public static final int DPCHAPPMSDCLIVVIDEODO = 94;
	public static final int DPCHAPPMSDCNAVADMINDATA = 95;
	public static final int DPCHAPPMSDCNAVADMINDO = 96;
	public static final int DPCHAPPMSDCNAVDO = 97;
	public static final int DPCHAPPMSDCNAVOPRDATA = 98;
	public static final int DPCHAPPMSDCNAVOPRDO = 99;
	public static final int DPCHAPPMSDCNAVPREDO = 100;
	public static final int DPCHAPPMSDCPRD1NDATADATA = 101;
	public static final int DPCHAPPMSDCPRD1NDATADO = 102;
	public static final int DPCHAPPMSDCPRDDETAILDATA = 103;
	public static final int DPCHAPPMSDCPRDDETAILDO = 104;
	public static final int DPCHAPPMSDCPRDDO = 105;
	public static final int DPCHAPPMSDCPRDLISTDATA = 106;
	public static final int DPCHAPPMSDCPRDLISTDO = 107;
	public static final int DPCHAPPMSDCPRDRECDO = 108;
	public static final int DPCHAPPMSDCPRSDETAILDATA = 109;
	public static final int DPCHAPPMSDCPRSDETAILDO = 110;
	public static final int DPCHAPPMSDCPRSDO = 111;
	public static final int DPCHAPPMSDCPRSLISTDATA = 112;
	public static final int DPCHAPPMSDCPRSLISTDO = 113;
	public static final int DPCHAPPMSDCPRSRECDO = 114;
	public static final int DPCHAPPMSDCRESUME = 115;
	public static final int DPCHAPPMSDCSCFACQUISDATA = 116;
	public static final int DPCHAPPMSDCSCFACQUISDO = 117;
	public static final int DPCHAPPMSDCSCFACTUDATA = 118;
	public static final int DPCHAPPMSDCSCFACTUDO = 119;
	public static final int DPCHAPPMSDCSCFDO = 120;
	public static final int DPCHAPPMSDCSCFPRCCTLDO = 121;
	public static final int DPCHAPPMSDCSCFSOURCEDATA = 122;
	public static final int DPCHAPPMSDCSCFSOURCEDO = 123;
	public static final int DPCHAPPMSDCUSGAACCESSDATA = 124;
	public static final int DPCHAPPMSDCUSGAACCESSDO = 125;
	public static final int DPCHAPPMSDCUSGDETAILDATA = 126;
	public static final int DPCHAPPMSDCUSGDETAILDO = 127;
	public static final int DPCHAPPMSDCUSGDO = 128;
	public static final int DPCHAPPMSDCUSGLISTDATA = 129;
	public static final int DPCHAPPMSDCUSGLISTDO = 130;
	public static final int DPCHAPPMSDCUSGMNUSERDATA = 131;
	public static final int DPCHAPPMSDCUSGMNUSERDO = 132;
	public static final int DPCHAPPMSDCUSGRECDO = 133;
	public static final int DPCHAPPMSDCUSR1NSESSIONDATA = 134;
	public static final int DPCHAPPMSDCUSR1NSESSIONDO = 135;
	public static final int DPCHAPPMSDCUSRAACCESSDATA = 136;
	public static final int DPCHAPPMSDCUSRAACCESSDO = 137;
	public static final int DPCHAPPMSDCUSRDETAILDATA = 138;
	public static final int DPCHAPPMSDCUSRDETAILDO = 139;
	public static final int DPCHAPPMSDCUSRDO = 140;
	public static final int DPCHAPPMSDCUSRLISTDATA = 141;
	public static final int DPCHAPPMSDCUSRLISTDO = 142;
	public static final int DPCHAPPMSDCUSRMNUSERGROUPDATA = 143;
	public static final int DPCHAPPMSDCUSRMNUSERGROUPDO = 144;
	public static final int DPCHAPPMSDCUSRRECDO = 145;
	public static final int DPCHAPPROOTMSDCLOGIN = 146;

	public static int getIx(
				String sref
			) {
		String s = sref.toLowerCase();

		if (s.equals("dpchengdlgmsdcfildownloaddata")) return DPCHENGDLGMSDCFILDOWNLOADDATA;
		if (s.equals("dpchengdlgmsdcnavloainidata")) return DPCHENGDLGMSDCNAVLOAINIDATA;
		if (s.equals("dpchengm2msessmsdcdata")) return DPCHENGM2MSESSMSDCDATA;
		if (s.equals("dpchengmsdcack")) return DPCHENGMSDCACK;
		if (s.equals("dpchengmsdcalert")) return DPCHENGMSDCALERT;
		if (s.equals("dpchengmsdcconfirm")) return DPCHENGMSDCCONFIRM;
		if (s.equals("dpchengmsdcdatapardata")) return DPCHENGMSDCDATAPARDATA;
		if (s.equals("dpchengmsdcdatdata")) return DPCHENGMSDCDATDATA;
		if (s.equals("dpchengmsdcdatdetaildata")) return DPCHENGMSDCDATDETAILDATA;
		if (s.equals("dpchengmsdcdatheadbardata")) return DPCHENGMSDCDATHEADBARDATA;
		if (s.equals("dpchengmsdcdatlistdata")) return DPCHENGMSDCDATLISTDATA;
		if (s.equals("dpchengmsdcdatrecdata")) return DPCHENGMSDCDATRECDATA;
		if (s.equals("dpchengmsdcdatref1nfiledata")) return DPCHENGMSDCDATREF1NFILEDATA;
		if (s.equals("dpchengmsdcfildata")) return DPCHENGMSDCFILDATA;
		if (s.equals("dpchengmsdcfildetaildata")) return DPCHENGMSDCFILDETAILDATA;
		if (s.equals("dpchengmsdcfilheadbardata")) return DPCHENGMSDCFILHEADBARDATA;
		if (s.equals("dpchengmsdcfillistdata")) return DPCHENGMSDCFILLISTDATA;
		if (s.equals("dpchengmsdcfilrecdata")) return DPCHENGMSDCFILRECDATA;
		if (s.equals("dpchengmsdclivaligndata")) return DPCHENGMSDCLIVALIGNDATA;
		if (s.equals("dpchengmsdclivdata")) return DPCHENGMSDCLIVDATA;
		if (s.equals("dpchengmsdclivheadbardata")) return DPCHENGMSDCLIVHEADBARDATA;
		if (s.equals("dpchengmsdclivscilldata")) return DPCHENGMSDCLIVSCILLDATA;
		if (s.equals("dpchengmsdclivtrackdata")) return DPCHENGMSDCLIVTRACKDATA;
		if (s.equals("dpchengmsdclivvideodata")) return DPCHENGMSDCLIVVIDEODATA;
		if (s.equals("dpchengmsdclivvideolive")) return DPCHENGMSDCLIVVIDEOLIVE;
		if (s.equals("dpchengmsdcnavadmindata")) return DPCHENGMSDCNAVADMINDATA;
		if (s.equals("dpchengmsdcnavdata")) return DPCHENGMSDCNAVDATA;
		if (s.equals("dpchengmsdcnavheadbardata")) return DPCHENGMSDCNAVHEADBARDATA;
		if (s.equals("dpchengmsdcnavoprdata")) return DPCHENGMSDCNAVOPRDATA;
		if (s.equals("dpchengmsdcnavpredata")) return DPCHENGMSDCNAVPREDATA;
		if (s.equals("dpchengmsdcprd1ndatadata")) return DPCHENGMSDCPRD1NDATADATA;
		if (s.equals("dpchengmsdcprddata")) return DPCHENGMSDCPRDDATA;
		if (s.equals("dpchengmsdcprddetaildata")) return DPCHENGMSDCPRDDETAILDATA;
		if (s.equals("dpchengmsdcprdheadbardata")) return DPCHENGMSDCPRDHEADBARDATA;
		if (s.equals("dpchengmsdcprdlistdata")) return DPCHENGMSDCPRDLISTDATA;
		if (s.equals("dpchengmsdcprdrecdata")) return DPCHENGMSDCPRDRECDATA;
		if (s.equals("dpchengmsdcprsdata")) return DPCHENGMSDCPRSDATA;
		if (s.equals("dpchengmsdcprsdetaildata")) return DPCHENGMSDCPRSDETAILDATA;
		if (s.equals("dpchengmsdcprsheadbardata")) return DPCHENGMSDCPRSHEADBARDATA;
		if (s.equals("dpchengmsdcprslistdata")) return DPCHENGMSDCPRSLISTDATA;
		if (s.equals("dpchengmsdcprsrecdata")) return DPCHENGMSDCPRSRECDATA;
		if (s.equals("dpchengmsdcscfacquisdata")) return DPCHENGMSDCSCFACQUISDATA;
		if (s.equals("dpchengmsdcscfactudata")) return DPCHENGMSDCSCFACTUDATA;
		if (s.equals("dpchengmsdcscfdata")) return DPCHENGMSDCSCFDATA;
		if (s.equals("dpchengmsdcscfheadbardata")) return DPCHENGMSDCSCFHEADBARDATA;
		if (s.equals("dpchengmsdcscfprcctldata")) return DPCHENGMSDCSCFPRCCTLDATA;
		if (s.equals("dpchengmsdcscfsourcedata")) return DPCHENGMSDCSCFSOURCEDATA;
		if (s.equals("dpchengmsdcsuspend")) return DPCHENGMSDCSUSPEND;
		if (s.equals("dpchengmsdcusgaaccessdata")) return DPCHENGMSDCUSGAACCESSDATA;
		if (s.equals("dpchengmsdcusgdata")) return DPCHENGMSDCUSGDATA;
		if (s.equals("dpchengmsdcusgdetaildata")) return DPCHENGMSDCUSGDETAILDATA;
		if (s.equals("dpchengmsdcusgheadbardata")) return DPCHENGMSDCUSGHEADBARDATA;
		if (s.equals("dpchengmsdcusglistdata")) return DPCHENGMSDCUSGLISTDATA;
		if (s.equals("dpchengmsdcusgmnuserdata")) return DPCHENGMSDCUSGMNUSERDATA;
		if (s.equals("dpchengmsdcusgrecdata")) return DPCHENGMSDCUSGRECDATA;
		if (s.equals("dpchengmsdcusr1nsessiondata")) return DPCHENGMSDCUSR1NSESSIONDATA;
		if (s.equals("dpchengmsdcusraaccessdata")) return DPCHENGMSDCUSRAACCESSDATA;
		if (s.equals("dpchengmsdcusrdata")) return DPCHENGMSDCUSRDATA;
		if (s.equals("dpchengmsdcusrdetaildata")) return DPCHENGMSDCUSRDETAILDATA;
		if (s.equals("dpchengmsdcusrheadbardata")) return DPCHENGMSDCUSRHEADBARDATA;
		if (s.equals("dpchengmsdcusrlistdata")) return DPCHENGMSDCUSRLISTDATA;
		if (s.equals("dpchengmsdcusrmnusergroupdata")) return DPCHENGMSDCUSRMNUSERGROUPDATA;
		if (s.equals("dpchengmsdcusrrecdata")) return DPCHENGMSDCUSRRECDATA;
		if (s.equals("dpchengrootmsdcdata")) return DPCHENGROOTMSDCDATA;
		if (s.equals("dpchengsessmsdcdata")) return DPCHENGSESSMSDCDATA;
		if (s.equals("dpchappdlgmsdcfildownloaddo")) return DPCHAPPDLGMSDCFILDOWNLOADDO;
		if (s.equals("dpchappdlgmsdcnavloainidata")) return DPCHAPPDLGMSDCNAVLOAINIDATA;
		if (s.equals("dpchappdlgmsdcnavloainido")) return DPCHAPPDLGMSDCNAVLOAINIDO;
		if (s.equals("dpchappmsdcalert")) return DPCHAPPMSDCALERT;
		if (s.equals("dpchappmsdcdatapardata")) return DPCHAPPMSDCDATAPARDATA;
		if (s.equals("dpchappmsdcdatapardo")) return DPCHAPPMSDCDATAPARDO;
		if (s.equals("dpchappmsdcdatdetaildata")) return DPCHAPPMSDCDATDETAILDATA;
		if (s.equals("dpchappmsdcdatdetaildo")) return DPCHAPPMSDCDATDETAILDO;
		if (s.equals("dpchappmsdcdatdo")) return DPCHAPPMSDCDATDO;
		if (s.equals("dpchappmsdcdatlistdata")) return DPCHAPPMSDCDATLISTDATA;
		if (s.equals("dpchappmsdcdatlistdo")) return DPCHAPPMSDCDATLISTDO;
		if (s.equals("dpchappmsdcdatrecdo")) return DPCHAPPMSDCDATRECDO;
		if (s.equals("dpchappmsdcdatref1nfiledata")) return DPCHAPPMSDCDATREF1NFILEDATA;
		if (s.equals("dpchappmsdcdatref1nfiledo")) return DPCHAPPMSDCDATREF1NFILEDO;
		if (s.equals("dpchappmsdcfildetaildata")) return DPCHAPPMSDCFILDETAILDATA;
		if (s.equals("dpchappmsdcfildetaildo")) return DPCHAPPMSDCFILDETAILDO;
		if (s.equals("dpchappmsdcfildo")) return DPCHAPPMSDCFILDO;
		if (s.equals("dpchappmsdcfillistdata")) return DPCHAPPMSDCFILLISTDATA;
		if (s.equals("dpchappmsdcfillistdo")) return DPCHAPPMSDCFILLISTDO;
		if (s.equals("dpchappmsdcfilrecdo")) return DPCHAPPMSDCFILRECDO;
		if (s.equals("dpchappmsdcinit")) return DPCHAPPMSDCINIT;
		if (s.equals("dpchappmsdclivaligndata")) return DPCHAPPMSDCLIVALIGNDATA;
		if (s.equals("dpchappmsdclivaligndo")) return DPCHAPPMSDCLIVALIGNDO;
		if (s.equals("dpchappmsdclivdo")) return DPCHAPPMSDCLIVDO;
		if (s.equals("dpchappmsdclivscilldata")) return DPCHAPPMSDCLIVSCILLDATA;
		if (s.equals("dpchappmsdclivscilldo")) return DPCHAPPMSDCLIVSCILLDO;
		if (s.equals("dpchappmsdclivtrackdo")) return DPCHAPPMSDCLIVTRACKDO;
		if (s.equals("dpchappmsdclivvideodata")) return DPCHAPPMSDCLIVVIDEODATA;
		if (s.equals("dpchappmsdclivvideodo")) return DPCHAPPMSDCLIVVIDEODO;
		if (s.equals("dpchappmsdcnavadmindata")) return DPCHAPPMSDCNAVADMINDATA;
		if (s.equals("dpchappmsdcnavadmindo")) return DPCHAPPMSDCNAVADMINDO;
		if (s.equals("dpchappmsdcnavdo")) return DPCHAPPMSDCNAVDO;
		if (s.equals("dpchappmsdcnavoprdata")) return DPCHAPPMSDCNAVOPRDATA;
		if (s.equals("dpchappmsdcnavoprdo")) return DPCHAPPMSDCNAVOPRDO;
		if (s.equals("dpchappmsdcnavpredo")) return DPCHAPPMSDCNAVPREDO;
		if (s.equals("dpchappmsdcprd1ndatadata")) return DPCHAPPMSDCPRD1NDATADATA;
		if (s.equals("dpchappmsdcprd1ndatado")) return DPCHAPPMSDCPRD1NDATADO;
		if (s.equals("dpchappmsdcprddetaildata")) return DPCHAPPMSDCPRDDETAILDATA;
		if (s.equals("dpchappmsdcprddetaildo")) return DPCHAPPMSDCPRDDETAILDO;
		if (s.equals("dpchappmsdcprddo")) return DPCHAPPMSDCPRDDO;
		if (s.equals("dpchappmsdcprdlistdata")) return DPCHAPPMSDCPRDLISTDATA;
		if (s.equals("dpchappmsdcprdlistdo")) return DPCHAPPMSDCPRDLISTDO;
		if (s.equals("dpchappmsdcprdrecdo")) return DPCHAPPMSDCPRDRECDO;
		if (s.equals("dpchappmsdcprsdetaildata")) return DPCHAPPMSDCPRSDETAILDATA;
		if (s.equals("dpchappmsdcprsdetaildo")) return DPCHAPPMSDCPRSDETAILDO;
		if (s.equals("dpchappmsdcprsdo")) return DPCHAPPMSDCPRSDO;
		if (s.equals("dpchappmsdcprslistdata")) return DPCHAPPMSDCPRSLISTDATA;
		if (s.equals("dpchappmsdcprslistdo")) return DPCHAPPMSDCPRSLISTDO;
		if (s.equals("dpchappmsdcprsrecdo")) return DPCHAPPMSDCPRSRECDO;
		if (s.equals("dpchappmsdcresume")) return DPCHAPPMSDCRESUME;
		if (s.equals("dpchappmsdcscfacquisdata")) return DPCHAPPMSDCSCFACQUISDATA;
		if (s.equals("dpchappmsdcscfacquisdo")) return DPCHAPPMSDCSCFACQUISDO;
		if (s.equals("dpchappmsdcscfactudata")) return DPCHAPPMSDCSCFACTUDATA;
		if (s.equals("dpchappmsdcscfactudo")) return DPCHAPPMSDCSCFACTUDO;
		if (s.equals("dpchappmsdcscfdo")) return DPCHAPPMSDCSCFDO;
		if (s.equals("dpchappmsdcscfprcctldo")) return DPCHAPPMSDCSCFPRCCTLDO;
		if (s.equals("dpchappmsdcscfsourcedata")) return DPCHAPPMSDCSCFSOURCEDATA;
		if (s.equals("dpchappmsdcscfsourcedo")) return DPCHAPPMSDCSCFSOURCEDO;
		if (s.equals("dpchappmsdcusgaaccessdata")) return DPCHAPPMSDCUSGAACCESSDATA;
		if (s.equals("dpchappmsdcusgaaccessdo")) return DPCHAPPMSDCUSGAACCESSDO;
		if (s.equals("dpchappmsdcusgdetaildata")) return DPCHAPPMSDCUSGDETAILDATA;
		if (s.equals("dpchappmsdcusgdetaildo")) return DPCHAPPMSDCUSGDETAILDO;
		if (s.equals("dpchappmsdcusgdo")) return DPCHAPPMSDCUSGDO;
		if (s.equals("dpchappmsdcusglistdata")) return DPCHAPPMSDCUSGLISTDATA;
		if (s.equals("dpchappmsdcusglistdo")) return DPCHAPPMSDCUSGLISTDO;
		if (s.equals("dpchappmsdcusgmnuserdata")) return DPCHAPPMSDCUSGMNUSERDATA;
		if (s.equals("dpchappmsdcusgmnuserdo")) return DPCHAPPMSDCUSGMNUSERDO;
		if (s.equals("dpchappmsdcusgrecdo")) return DPCHAPPMSDCUSGRECDO;
		if (s.equals("dpchappmsdcusr1nsessiondata")) return DPCHAPPMSDCUSR1NSESSIONDATA;
		if (s.equals("dpchappmsdcusr1nsessiondo")) return DPCHAPPMSDCUSR1NSESSIONDO;
		if (s.equals("dpchappmsdcusraaccessdata")) return DPCHAPPMSDCUSRAACCESSDATA;
		if (s.equals("dpchappmsdcusraaccessdo")) return DPCHAPPMSDCUSRAACCESSDO;
		if (s.equals("dpchappmsdcusrdetaildata")) return DPCHAPPMSDCUSRDETAILDATA;
		if (s.equals("dpchappmsdcusrdetaildo")) return DPCHAPPMSDCUSRDETAILDO;
		if (s.equals("dpchappmsdcusrdo")) return DPCHAPPMSDCUSRDO;
		if (s.equals("dpchappmsdcusrlistdata")) return DPCHAPPMSDCUSRLISTDATA;
		if (s.equals("dpchappmsdcusrlistdo")) return DPCHAPPMSDCUSRLISTDO;
		if (s.equals("dpchappmsdcusrmnusergroupdata")) return DPCHAPPMSDCUSRMNUSERGROUPDATA;
		if (s.equals("dpchappmsdcusrmnusergroupdo")) return DPCHAPPMSDCUSRMNUSERGROUPDO;
		if (s.equals("dpchappmsdcusrrecdo")) return DPCHAPPMSDCUSRRECDO;
		if (s.equals("dpchapprootmsdclogin")) return DPCHAPPROOTMSDCLOGIN;

		return 0;
	};
	
	public static String getSref(
				int ix
			) {
		if (ix == DPCHENGDLGMSDCFILDOWNLOADDATA) return("DpchEngDlgMsdcFilDownloadData");
		if (ix == DPCHENGDLGMSDCNAVLOAINIDATA) return("DpchEngDlgMsdcNavLoainiData");
		if (ix == DPCHENGM2MSESSMSDCDATA) return("DpchEngM2msessMsdcData");
		if (ix == DPCHENGMSDCACK) return("DpchEngMsdcAck");
		if (ix == DPCHENGMSDCALERT) return("DpchEngMsdcAlert");
		if (ix == DPCHENGMSDCCONFIRM) return("DpchEngMsdcConfirm");
		if (ix == DPCHENGMSDCDATAPARDATA) return("DpchEngMsdcDatAParData");
		if (ix == DPCHENGMSDCDATDATA) return("DpchEngMsdcDatData");
		if (ix == DPCHENGMSDCDATDETAILDATA) return("DpchEngMsdcDatDetailData");
		if (ix == DPCHENGMSDCDATHEADBARDATA) return("DpchEngMsdcDatHeadbarData");
		if (ix == DPCHENGMSDCDATLISTDATA) return("DpchEngMsdcDatListData");
		if (ix == DPCHENGMSDCDATRECDATA) return("DpchEngMsdcDatRecData");
		if (ix == DPCHENGMSDCDATREF1NFILEDATA) return("DpchEngMsdcDatRef1NFileData");
		if (ix == DPCHENGMSDCFILDATA) return("DpchEngMsdcFilData");
		if (ix == DPCHENGMSDCFILDETAILDATA) return("DpchEngMsdcFilDetailData");
		if (ix == DPCHENGMSDCFILHEADBARDATA) return("DpchEngMsdcFilHeadbarData");
		if (ix == DPCHENGMSDCFILLISTDATA) return("DpchEngMsdcFilListData");
		if (ix == DPCHENGMSDCFILRECDATA) return("DpchEngMsdcFilRecData");
		if (ix == DPCHENGMSDCLIVALIGNDATA) return("DpchEngMsdcLivAlignData");
		if (ix == DPCHENGMSDCLIVDATA) return("DpchEngMsdcLivData");
		if (ix == DPCHENGMSDCLIVHEADBARDATA) return("DpchEngMsdcLivHeadbarData");
		if (ix == DPCHENGMSDCLIVSCILLDATA) return("DpchEngMsdcLivScillData");
		if (ix == DPCHENGMSDCLIVTRACKDATA) return("DpchEngMsdcLivTrackData");
		if (ix == DPCHENGMSDCLIVVIDEODATA) return("DpchEngMsdcLivVideoData");
		if (ix == DPCHENGMSDCLIVVIDEOLIVE) return("DpchEngMsdcLivVideoLive");
		if (ix == DPCHENGMSDCNAVADMINDATA) return("DpchEngMsdcNavAdminData");
		if (ix == DPCHENGMSDCNAVDATA) return("DpchEngMsdcNavData");
		if (ix == DPCHENGMSDCNAVHEADBARDATA) return("DpchEngMsdcNavHeadbarData");
		if (ix == DPCHENGMSDCNAVOPRDATA) return("DpchEngMsdcNavOprData");
		if (ix == DPCHENGMSDCNAVPREDATA) return("DpchEngMsdcNavPreData");
		if (ix == DPCHENGMSDCPRD1NDATADATA) return("DpchEngMsdcPrd1NDataData");
		if (ix == DPCHENGMSDCPRDDATA) return("DpchEngMsdcPrdData");
		if (ix == DPCHENGMSDCPRDDETAILDATA) return("DpchEngMsdcPrdDetailData");
		if (ix == DPCHENGMSDCPRDHEADBARDATA) return("DpchEngMsdcPrdHeadbarData");
		if (ix == DPCHENGMSDCPRDLISTDATA) return("DpchEngMsdcPrdListData");
		if (ix == DPCHENGMSDCPRDRECDATA) return("DpchEngMsdcPrdRecData");
		if (ix == DPCHENGMSDCPRSDATA) return("DpchEngMsdcPrsData");
		if (ix == DPCHENGMSDCPRSDETAILDATA) return("DpchEngMsdcPrsDetailData");
		if (ix == DPCHENGMSDCPRSHEADBARDATA) return("DpchEngMsdcPrsHeadbarData");
		if (ix == DPCHENGMSDCPRSLISTDATA) return("DpchEngMsdcPrsListData");
		if (ix == DPCHENGMSDCPRSRECDATA) return("DpchEngMsdcPrsRecData");
		if (ix == DPCHENGMSDCSCFACQUISDATA) return("DpchEngMsdcScfAcquisData");
		if (ix == DPCHENGMSDCSCFACTUDATA) return("DpchEngMsdcScfActuData");
		if (ix == DPCHENGMSDCSCFDATA) return("DpchEngMsdcScfData");
		if (ix == DPCHENGMSDCSCFHEADBARDATA) return("DpchEngMsdcScfHeadbarData");
		if (ix == DPCHENGMSDCSCFPRCCTLDATA) return("DpchEngMsdcScfPrcctlData");
		if (ix == DPCHENGMSDCSCFSOURCEDATA) return("DpchEngMsdcScfSourceData");
		if (ix == DPCHENGMSDCSUSPEND) return("DpchEngMsdcSuspend");
		if (ix == DPCHENGMSDCUSGAACCESSDATA) return("DpchEngMsdcUsgAAccessData");
		if (ix == DPCHENGMSDCUSGDATA) return("DpchEngMsdcUsgData");
		if (ix == DPCHENGMSDCUSGDETAILDATA) return("DpchEngMsdcUsgDetailData");
		if (ix == DPCHENGMSDCUSGHEADBARDATA) return("DpchEngMsdcUsgHeadbarData");
		if (ix == DPCHENGMSDCUSGLISTDATA) return("DpchEngMsdcUsgListData");
		if (ix == DPCHENGMSDCUSGMNUSERDATA) return("DpchEngMsdcUsgMNUserData");
		if (ix == DPCHENGMSDCUSGRECDATA) return("DpchEngMsdcUsgRecData");
		if (ix == DPCHENGMSDCUSR1NSESSIONDATA) return("DpchEngMsdcUsr1NSessionData");
		if (ix == DPCHENGMSDCUSRAACCESSDATA) return("DpchEngMsdcUsrAAccessData");
		if (ix == DPCHENGMSDCUSRDATA) return("DpchEngMsdcUsrData");
		if (ix == DPCHENGMSDCUSRDETAILDATA) return("DpchEngMsdcUsrDetailData");
		if (ix == DPCHENGMSDCUSRHEADBARDATA) return("DpchEngMsdcUsrHeadbarData");
		if (ix == DPCHENGMSDCUSRLISTDATA) return("DpchEngMsdcUsrListData");
		if (ix == DPCHENGMSDCUSRMNUSERGROUPDATA) return("DpchEngMsdcUsrMNUsergroupData");
		if (ix == DPCHENGMSDCUSRRECDATA) return("DpchEngMsdcUsrRecData");
		if (ix == DPCHENGROOTMSDCDATA) return("DpchEngRootMsdcData");
		if (ix == DPCHENGSESSMSDCDATA) return("DpchEngSessMsdcData");
		if (ix == DPCHAPPDLGMSDCFILDOWNLOADDO) return("DpchAppDlgMsdcFilDownloadDo");
		if (ix == DPCHAPPDLGMSDCNAVLOAINIDATA) return("DpchAppDlgMsdcNavLoainiData");
		if (ix == DPCHAPPDLGMSDCNAVLOAINIDO) return("DpchAppDlgMsdcNavLoainiDo");
		if (ix == DPCHAPPMSDCALERT) return("DpchAppMsdcAlert");
		if (ix == DPCHAPPMSDCDATAPARDATA) return("DpchAppMsdcDatAParData");
		if (ix == DPCHAPPMSDCDATAPARDO) return("DpchAppMsdcDatAParDo");
		if (ix == DPCHAPPMSDCDATDETAILDATA) return("DpchAppMsdcDatDetailData");
		if (ix == DPCHAPPMSDCDATDETAILDO) return("DpchAppMsdcDatDetailDo");
		if (ix == DPCHAPPMSDCDATDO) return("DpchAppMsdcDatDo");
		if (ix == DPCHAPPMSDCDATLISTDATA) return("DpchAppMsdcDatListData");
		if (ix == DPCHAPPMSDCDATLISTDO) return("DpchAppMsdcDatListDo");
		if (ix == DPCHAPPMSDCDATRECDO) return("DpchAppMsdcDatRecDo");
		if (ix == DPCHAPPMSDCDATREF1NFILEDATA) return("DpchAppMsdcDatRef1NFileData");
		if (ix == DPCHAPPMSDCDATREF1NFILEDO) return("DpchAppMsdcDatRef1NFileDo");
		if (ix == DPCHAPPMSDCFILDETAILDATA) return("DpchAppMsdcFilDetailData");
		if (ix == DPCHAPPMSDCFILDETAILDO) return("DpchAppMsdcFilDetailDo");
		if (ix == DPCHAPPMSDCFILDO) return("DpchAppMsdcFilDo");
		if (ix == DPCHAPPMSDCFILLISTDATA) return("DpchAppMsdcFilListData");
		if (ix == DPCHAPPMSDCFILLISTDO) return("DpchAppMsdcFilListDo");
		if (ix == DPCHAPPMSDCFILRECDO) return("DpchAppMsdcFilRecDo");
		if (ix == DPCHAPPMSDCINIT) return("DpchAppMsdcInit");
		if (ix == DPCHAPPMSDCLIVALIGNDATA) return("DpchAppMsdcLivAlignData");
		if (ix == DPCHAPPMSDCLIVALIGNDO) return("DpchAppMsdcLivAlignDo");
		if (ix == DPCHAPPMSDCLIVDO) return("DpchAppMsdcLivDo");
		if (ix == DPCHAPPMSDCLIVSCILLDATA) return("DpchAppMsdcLivScillData");
		if (ix == DPCHAPPMSDCLIVSCILLDO) return("DpchAppMsdcLivScillDo");
		if (ix == DPCHAPPMSDCLIVTRACKDO) return("DpchAppMsdcLivTrackDo");
		if (ix == DPCHAPPMSDCLIVVIDEODATA) return("DpchAppMsdcLivVideoData");
		if (ix == DPCHAPPMSDCLIVVIDEODO) return("DpchAppMsdcLivVideoDo");
		if (ix == DPCHAPPMSDCNAVADMINDATA) return("DpchAppMsdcNavAdminData");
		if (ix == DPCHAPPMSDCNAVADMINDO) return("DpchAppMsdcNavAdminDo");
		if (ix == DPCHAPPMSDCNAVDO) return("DpchAppMsdcNavDo");
		if (ix == DPCHAPPMSDCNAVOPRDATA) return("DpchAppMsdcNavOprData");
		if (ix == DPCHAPPMSDCNAVOPRDO) return("DpchAppMsdcNavOprDo");
		if (ix == DPCHAPPMSDCNAVPREDO) return("DpchAppMsdcNavPreDo");
		if (ix == DPCHAPPMSDCPRD1NDATADATA) return("DpchAppMsdcPrd1NDataData");
		if (ix == DPCHAPPMSDCPRD1NDATADO) return("DpchAppMsdcPrd1NDataDo");
		if (ix == DPCHAPPMSDCPRDDETAILDATA) return("DpchAppMsdcPrdDetailData");
		if (ix == DPCHAPPMSDCPRDDETAILDO) return("DpchAppMsdcPrdDetailDo");
		if (ix == DPCHAPPMSDCPRDDO) return("DpchAppMsdcPrdDo");
		if (ix == DPCHAPPMSDCPRDLISTDATA) return("DpchAppMsdcPrdListData");
		if (ix == DPCHAPPMSDCPRDLISTDO) return("DpchAppMsdcPrdListDo");
		if (ix == DPCHAPPMSDCPRDRECDO) return("DpchAppMsdcPrdRecDo");
		if (ix == DPCHAPPMSDCPRSDETAILDATA) return("DpchAppMsdcPrsDetailData");
		if (ix == DPCHAPPMSDCPRSDETAILDO) return("DpchAppMsdcPrsDetailDo");
		if (ix == DPCHAPPMSDCPRSDO) return("DpchAppMsdcPrsDo");
		if (ix == DPCHAPPMSDCPRSLISTDATA) return("DpchAppMsdcPrsListData");
		if (ix == DPCHAPPMSDCPRSLISTDO) return("DpchAppMsdcPrsListDo");
		if (ix == DPCHAPPMSDCPRSRECDO) return("DpchAppMsdcPrsRecDo");
		if (ix == DPCHAPPMSDCRESUME) return("DpchAppMsdcResume");
		if (ix == DPCHAPPMSDCSCFACQUISDATA) return("DpchAppMsdcScfAcquisData");
		if (ix == DPCHAPPMSDCSCFACQUISDO) return("DpchAppMsdcScfAcquisDo");
		if (ix == DPCHAPPMSDCSCFACTUDATA) return("DpchAppMsdcScfActuData");
		if (ix == DPCHAPPMSDCSCFACTUDO) return("DpchAppMsdcScfActuDo");
		if (ix == DPCHAPPMSDCSCFDO) return("DpchAppMsdcScfDo");
		if (ix == DPCHAPPMSDCSCFPRCCTLDO) return("DpchAppMsdcScfPrcctlDo");
		if (ix == DPCHAPPMSDCSCFSOURCEDATA) return("DpchAppMsdcScfSourceData");
		if (ix == DPCHAPPMSDCSCFSOURCEDO) return("DpchAppMsdcScfSourceDo");
		if (ix == DPCHAPPMSDCUSGAACCESSDATA) return("DpchAppMsdcUsgAAccessData");
		if (ix == DPCHAPPMSDCUSGAACCESSDO) return("DpchAppMsdcUsgAAccessDo");
		if (ix == DPCHAPPMSDCUSGDETAILDATA) return("DpchAppMsdcUsgDetailData");
		if (ix == DPCHAPPMSDCUSGDETAILDO) return("DpchAppMsdcUsgDetailDo");
		if (ix == DPCHAPPMSDCUSGDO) return("DpchAppMsdcUsgDo");
		if (ix == DPCHAPPMSDCUSGLISTDATA) return("DpchAppMsdcUsgListData");
		if (ix == DPCHAPPMSDCUSGLISTDO) return("DpchAppMsdcUsgListDo");
		if (ix == DPCHAPPMSDCUSGMNUSERDATA) return("DpchAppMsdcUsgMNUserData");
		if (ix == DPCHAPPMSDCUSGMNUSERDO) return("DpchAppMsdcUsgMNUserDo");
		if (ix == DPCHAPPMSDCUSGRECDO) return("DpchAppMsdcUsgRecDo");
		if (ix == DPCHAPPMSDCUSR1NSESSIONDATA) return("DpchAppMsdcUsr1NSessionData");
		if (ix == DPCHAPPMSDCUSR1NSESSIONDO) return("DpchAppMsdcUsr1NSessionDo");
		if (ix == DPCHAPPMSDCUSRAACCESSDATA) return("DpchAppMsdcUsrAAccessData");
		if (ix == DPCHAPPMSDCUSRAACCESSDO) return("DpchAppMsdcUsrAAccessDo");
		if (ix == DPCHAPPMSDCUSRDETAILDATA) return("DpchAppMsdcUsrDetailData");
		if (ix == DPCHAPPMSDCUSRDETAILDO) return("DpchAppMsdcUsrDetailDo");
		if (ix == DPCHAPPMSDCUSRDO) return("DpchAppMsdcUsrDo");
		if (ix == DPCHAPPMSDCUSRLISTDATA) return("DpchAppMsdcUsrListData");
		if (ix == DPCHAPPMSDCUSRLISTDO) return("DpchAppMsdcUsrListDo");
		if (ix == DPCHAPPMSDCUSRMNUSERGROUPDATA) return("DpchAppMsdcUsrMNUsergroupData");
		if (ix == DPCHAPPMSDCUSRMNUSERGROUPDO) return("DpchAppMsdcUsrMNUsergroupDo");
		if (ix == DPCHAPPMSDCUSRRECDO) return("DpchAppMsdcUsrRecDo");
		if (ix == DPCHAPPROOTMSDCLOGIN) return("DpchAppRootMsdcLogin");

		return "";
	};
};

