# file Makefile.inc
# make file paths for Msdc combined daemon, release msdccmbd_jack
# author Alexander Wirthmueller
# date created: 29 Aug 2018
# modified: 29 Aug 2018

SRCROOT = /home/mpsitech/src
LIBROOT = /home/mpsitech/lib
BINROOT = /home/mpsitech/bin
NDDSHOME = /home/mpsitech/rti_connext_dds-5.3.1
UASDKROOT = /home/mpsitech/flex_R400_2_1

