# file Makefile.inc
# make file paths for Msdc combined daemon, release msdccmbd_jack
# author Alexander Wirthmueller
# date created: 12 Sep 2018
# modified: 12 Sep 2018

SRCROOT = /home/mpsitech/src
LIBROOT = /home/mpsitech/lib
BINROOT = /home/mpsitech/bin
UASDKROOT = /home/mpsitech/flex_R400_2_1

