# file Makefile.inc
# make file paths for Msdc combined daemon, release msdccmbd_zedboard
# author Alexander Wirthmueller
# date created: 12 Sep 2018
# modified: 12 Sep 2018

SRCROOT = /home/root/src
LIBROOT = /home/root/lib
BINROOT = /home/root/bin
UASDKROOT = /home/root/flex_R400_2_1

