# file Makefile.inc
# make file paths for Msdc combined daemon, release msdccmbd_zedboard
# author Alexander Wirthmueller
# date created: 29 Aug 2018
# modified: 29 Aug 2018

SRCROOT = /home/root/src
LIBROOT = /home/root/lib
BINROOT = /home/root/bin
NDDSHOME = /home/root/rti_connext_dds-5.3.1
UASDKROOT = /home/root/flex_R400_2_1

