# file Makefile.inc
# make file paths for Msdc combined daemon, release msdccmbd_ungenio
# author Alexander Wirthmueller
# date created: 12 Sep 2018
# modified: 12 Sep 2018

SRCROOT = /Users/mpsitech/src
LIBROOT = /Users/mpsitech/lib
BINROOT = /Users/mpsitech/bin
UASDKROOT =

