# file Makefile.inc
# make file paths for Msdc combined daemon, release msdccmbd_ungenio
# author Alexander Wirthmueller
# date created: 29 Aug 2018
# modified: 29 Aug 2018

SRCROOT = /Users/mpsitech/src
LIBROOT = /Users/mpsitech/lib
BINROOT = /Users/mpsitech/bin
NDDSHOME = /Applications/rti_connext_dds-5.3.1
UASDKROOT =

